import {format, subDays} from 'date-fns';
import {ExerciseProgressResponse} from '../models/networkingObjects/responses/exerciseResponse';

export const exerciseLastMonthData: ExerciseProgressResponse = {
  id: 'f439ffsm',
  name: 'Deadlift',
  lastWeight: 45,
  averageWeight: 40,
  maxWeight: 45,
  graphData: [
    {date: format(new Date(), 'dd.MM.yy'), weight: 60},
    {date: format(subDays(new Date(), 3), 'dd.MM.yy'), weight: 58},
    {date: format(subDays(new Date(), 5), 'dd.MM.yy'), weight: 55},
    {date: format(subDays(new Date(), 7), 'dd.MM.yy'), weight: 55},
    {date: format(subDays(new Date(), 12), 'dd.MM.yy'), weight: 52.5},
    {date: format(subDays(new Date(), 18), 'dd.MM.yy'), weight: 52.5},
    {date: format(subDays(new Date(), 23), 'dd.MM.yy'), weight: 52.5},
  ],
};

export const exerciseLast3MonthsData: ExerciseProgressResponse = {
  id: 'f439ffsm',
  name: 'Deadlift',
  lastWeight: 45,
  averageWeight: 40,
  maxWeight: 45,
  graphData: [
    {date: format(new Date(), 'dd.MM.yy'), weight: 60},
    {date: format(subDays(new Date(), 3), 'dd.MM.yy'), weight: 58},
    {date: format(subDays(new Date(), 5), 'dd.MM.yy'), weight: 55},
    {date: format(subDays(new Date(), 7), 'dd.MM.yy'), weight: 55},
    {date: format(subDays(new Date(), 12), 'dd.MM.yy'), weight: 52.5},
    {date: format(subDays(new Date(), 18), 'dd.MM.yy'), weight: 52.5},
    {date: format(subDays(new Date(), 23), 'dd.MM.yy'), weight: 52.5},
    {date: format(subDays(new Date(), 40), 'dd.MM.yy'), weight: 50},
    {date: format(subDays(new Date(), 43), 'dd.MM.yy'), weight: 47},
    {date: format(subDays(new Date(), 50), 'dd.MM.yy'), weight: 47},
    {date: format(subDays(new Date(), 63), 'dd.MM.yy'), weight: 45},
    {date: format(subDays(new Date(), 70), 'dd.MM.yy'), weight: 42},
    {date: format(subDays(new Date(), 83), 'dd.MM.yy'), weight: 42.5},
    {date: format(subDays(new Date(), 87), 'dd.MM.yy'), weight: 42.5},
  ],
};

export const exerciseLast6MonthsData: ExerciseProgressResponse = {
  id: 'f439ffsm',
  name: 'Deadlift',
  lastWeight: 45,
  averageWeight: 40,
  maxWeight: 45,
  graphData: [
    {date: format(new Date(), 'dd.MM.yy'), weight: 60},
    {date: format(subDays(new Date(), 3), 'dd.MM.yy'), weight: 58},
    {date: format(subDays(new Date(), 5), 'dd.MM.yy'), weight: 55},
    {date: format(subDays(new Date(), 7), 'dd.MM.yy'), weight: 55},
    {date: format(subDays(new Date(), 12), 'dd.MM.yy'), weight: 52.5},
    {date: format(subDays(new Date(), 18), 'dd.MM.yy'), weight: 52.5},
    {date: format(subDays(new Date(), 23), 'dd.MM.yy'), weight: 52.5},
    {date: format(subDays(new Date(), 40), 'dd.MM.yy'), weight: 50},
    {date: format(subDays(new Date(), 43), 'dd.MM.yy'), weight: 47},
    {date: format(subDays(new Date(), 50), 'dd.MM.yy'), weight: 47},
    {date: format(subDays(new Date(), 63), 'dd.MM.yy'), weight: 45},
    {date: format(subDays(new Date(), 70), 'dd.MM.yy'), weight: 42},
    {date: format(subDays(new Date(), 83), 'dd.MM.yy'), weight: 42.5},
    {date: format(subDays(new Date(), 87), 'dd.MM.yy'), weight: 42.5},
    {date: format(subDays(new Date(), 95), 'dd.MM.yy'), weight: 40.5},
    {date: format(subDays(new Date(), 104), 'dd.MM.yy'), weight: 38},
    {date: format(subDays(new Date(), 110), 'dd.MM.yy'), weight: 38},
    {date: format(subDays(new Date(), 116), 'dd.MM.yy'), weight: 36.5},
    {date: format(subDays(new Date(), 123), 'dd.MM.yy'), weight: 36},
    {date: format(subDays(new Date(), 126), 'dd.MM.yy'), weight: 32},
    {date: format(subDays(new Date(), 140), 'dd.MM.yy'), weight: 32},
    {date: format(subDays(new Date(), 135), 'dd.MM.yy'), weight: 30},
  ],
};
